---
abstract: 'Add an AVAILABILITY pod section'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
  - 'Nigel Metheringham <nigelm@cpan.org>'
  - 'Mark Gardner <mjgardner@cpan.org>'
build_requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102340, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Weaver-Section-Availability
provides:
  Pod::Weaver::Section::Availability:
    file: lib/Pod/Weaver/Section/Availability.pm
    version: 1.102570
requires:
  Dist::Zilla::Plugin::Bugtracker: 0
  Dist::Zilla::Plugin::Homepage: 0
  Moose: 0
  Moose::Autobox: 0
  Pod::Weaver::Role::Section: 0
  namespace::autoclean: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Pod-Weaver-Section-Availability
  homepage: http://search.cpan.org/dist/Pod-Weaver-Section-Availability/
  repository: http://github.com/hanekomu/Pod-Weaver-Section-Availability
version: 1.102570
